language: php
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

## Build matrix for lowest and highest possible targets
matrix:
  include:
    - php: 7.2
      script:
        - vendor/bin/psalm
        - vendor/bin/phpunit
        - vendor/bin/phpbench run
      env: dependencies=lowest
    - php: 7.3
      script:
        - vendor/bin/psalm
        - vendor/bin/phpunit
        - vendor/bin/phpbench run
      env: dependencies=lowest
    - php: 7.4
      script:
        - vendor/bin/psalm
        - vendor/bin/phpunit
        - vendor/bin/phpbench run
      env: dependencies=highest
    - php: 8.0
      script:
        - vendor/bin/psalm
        - vendor/bin/phpunit
        - vendor/bin/phpbench run
      env: dependencies=highest

    - php: 8.1
      script:
        - vendor/bin/psalm
        - vendor/bin/phpunit
        - vendor/bin/phpbench run
      env: dependencies=highest
## Update composer and run the appropriate composer command
before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i
